#############################################################
# Development Config file for CLI: ep-migrate
# for fully commented config file run: yarn start -h 
#############################################################

logger:
  logSummary2Console: true
  logLevel: info
  logFile: ./logs/ep-migrate.log
  prettyPrint: true
  log2Stdout: false
  epSdkLogLevel: silent
epV1:
  apiUrl: https://api.solace.cloud
  token: ${EP_MIGRATE_CLI_SOLACE_CLOUD_TOKEN_V1}
epV2:
  apiUrl: https://api.solace.cloud
  token: ${EP_MIGRATE_CLI_SOLACE_CLOUD_TOKEN_V2}
migrate:
  epV2:
    # applicationDomainPrefix: 'epV1/'
    applicationDomainPrefix: 'epV1/cto/'
    # applicationDomainPrefix: 'epV1/solace-iot-team/'
    versions:
      initialVersion: 1.0.0
      versionStrategy: bump_patch      
      state: Draft
  enums:
    epV2:
      applicationDomainName: 'enums'
      versions:
        initialVersion: 2.0.0
        versionStrategy: bump_patch      
        state: Released
  applicationDomains:
    epV2:
  schemas:
    epV2:
      versions:
        initialVersion: 1.0.0
        versionStrategy: bump_patch      
        state: Released

  
